### ISSUE TITLE
Xcake crashes when adding third-party frameworks

### ISSUE THREAD

**Issue by felipesabino** [jcampbell05/xcake#105]
I am currently trying to add a third-party framework but Xcake is crashing right when it reaches my `.Framework` file.

Here is Xcake's output log with the stacktrace:

```
- Reading Cakefile
  - Creating Project
  - Creating Target<MyProject>
  - Resolving Project
  - Resolving Target<MyProject>
- Adding MyProject
- Adding MyProject/App
- Adding MyProject/App/AppDelegate.h
- Adding MyProject/App/AppDelegate.m
- Adding MyProject/Library.framework
XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/file_reference_installer/link_library_file_reference_installer.rb:11:in `add_file_reference_to_target': undefined method `add_file_reference' for nil:NilClass (NoMethodError)
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/file_reference_installer.rb:79:in `block in visit_node'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/file_reference_installer.rb:78:in `each'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/file_reference_installer.rb:78:in `visit_node'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/file_reference_installer/link_library_file_reference_installer.rb:15:in `visit_node'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/visitor.rb:45:in `visit'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:129:in `accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/generator/target_file_reference_generator.rb:48:in `visit_node'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/visitor.rb:45:in `visit'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:129:in `accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:132:in `block in accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:131:in `each'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:131:in `accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:132:in `block in accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:131:in `each'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/node.rb:131:in `accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/generator/target_file_reference_generator.rb:34:in `visit_project'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/visitor.rb:45:in `visit'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/project.rb:82:in `accept'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/command/make.rb:25:in `block in run'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/command/make.rb:23:in `each'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/lib/xcake/command/make.rb:23:in `run'
    from XXX/.rvm/gems/ruby-2.2.3/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
    from XXX/.rvm/gems/ruby-2.2.3/gems/xcake-0.6.25/bin/xcake:7:in `<top (required)>'
    from XXX/.rvm/gems/ruby-2.2.3/bin/xcake:23:in `load'
    from XXX/.rvm/gems/ruby-2.2.3/bin/xcake:23:in `<main>'
    from XXX/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from XXX/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Some environment info:

| - | Version |
| --- | --- |
| xcake | 0.6.25 |
| fastlane-plugin-xcake | 0.1.0 |
| fastlane | 1.97.2 |
| ruby | 2.2.3 |
| OS X | 10.11.6 |
| XCode | 7.3 |

**Comment by jcampbell05** [comment]
@felipesabino  sorry for slow response, do you have an example Cakefile to hand ?

**Comment by felipesabino** [comment]
@jcampbell05 Here it is https://gist.github.com/felipesabino/17e428881f3ba3d588a659495226ad17

**Comment by jcampbell05** [comment]
@felipesabino Thanks for this, investigating this now :)  Do you know which framework is having the issue ?

**Comment by jcampbell05** [comment]
Closing this for now, but could you try this with xcake 0.8.0 and see if it still has the same issue.
