### ISSUE TITLE
Crash if folder name contains some special characters

### ISSUE THREAD

**Issue by frankdilo** [jcampbell05/xcake#156]
I have found `xcake` to crash if, among the files that I have defined to be include in the project, there is a folder which contains either a dash (`-`) or a dot (`.`) in its name. This should work because those characters are allowed in Xcode groups' names.

This is the error message:

```
/Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/xcode/project.rb:118:in `file_reference_for_path': undefined method `dirname' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ff1ed931b60> (NoMethodError)
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/context/xcodeproj_context.rb:56:in `file_reference_for_path'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:33:in `include_file_for_path_and_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:26:in `block in visit_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:25:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/generator/target_file_reference_generator.rb:25:in `visit_target'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/frankdilo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
	from /Users/frankdilo/.rbenv/versions/2.2.2/bin/xcake:23:in `load'
	from /Users/frankdilo/.rbenv/versions/2.2.2/bin/xcake:23:in `<main>'
```

**Comment by jcampbell05** [comment]
@frankdilo great catch :) I'll look into this right away.

Can you tell me what Xcodeproj version you are using ?

**Comment by frankdilo** [comment]
Sure, `xcodeproj (1.4.2)`. Thanks for the quick reply.

**Comment by jcampbell05** [comment]
@frankdilo awesome I'll take a look, I've also release a `0.8.9`which should fix that problem with it crashing 3 out of 5 times when generating :)
