### ISSUE TITLE
`eval': undefined method `ruby' for #<Xcake::Command:0x007f8eb5ac9900> (NoMethodError)

### ISSUE THREAD

**Issue by intfrr** [jcampbell05/xcake#30]
According to 

`http://www.rubydoc.info/gems/xcake/file/docs/Getting%20Started.md`

The Cakefile must have `ruby Project.new do |c| end` but when I do `xcake` gives me this error:

```
$ xcake
Reading Cakefile...
~/.rvm/gems/ruby-2.1.6/gems/xcake-0.4.8/lib/xcake/command.rb:19:in `eval': undefined method `ruby' for #<Xcake::Command:0x007f8eb5ac9900> (NoMethodError)
	from /Users/dragon/.rvm/gems/ruby-2.1.6/gems/xcake-0.4.8/lib/xcake/command.rb:19:in `eval'


	from ~/.rvm/gems/ruby-2.1.6/gems/xcake-0.4.8/lib/xcake/command.rb:19:in `run'
	from ~/.rvm/gems/ruby-2.1.6/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
	from ~/.rvm/gems/ruby-2.1.6/gems/xcake-0.4.8/bin/xcake:5:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.1.6/bin/xcake:23:in `load'
	from ~/.rvm/gems/ruby-2.1.6/bin/xcake:23:in `<main>'
	from ~/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```

But when I remove `ruby` from the Cakefile like you said in the README, it works.

**Comment by jcampbell05** [comment]
This looks like a typo in the documentation, thanks for pointing this out. I'll fix this.

**Comment by jcampbell05** [comment]
@intfrr  The latest documentation has been fix and the code blocks should show up correctly now. Thanks for reporting this :rocket:.

http://www.rubydoc.info/list/gems/xcake/file
