### ISSUE TITLE
New molinillo release is broken with xcake?

### ISSUE THREAD

**Issue by brennantaylor** [jcampbell05/xcake#80]
molinillo is resolving to 0.5.0 and that seems to be causing a problem.

```text
NoMethodError: undefined method `payload' for nil:NilClass
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/modules/specification_provider.rb:85:in `block in sort_dependencies'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/modules/specification_provider.rb:82:in `each'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/modules/specification_provider.rb:82:in `sort_by'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/modules/specification_provider.rb:82:in `sort_dependencies'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/resolution.rb:165:in `initial_state'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/resolution.rb:106:in `start_resolution'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/resolution.rb:64:in `resolve'
  vendor/bundle/ruby/2.0.0/gems/molinillo-0.5.0/lib/molinillo/resolver.rb:42:in `resolve'
  vendor/bundle/ruby/2.0.0/gems/xcake-0.6.19/lib/xcake/command/make.rb:32:in `run'
  vendor/bundle/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  vendor/bundle/ruby/2.0.0/gems/xcake-0.6.19/bin/xcake:5:in `<top (required)>'
  vendor/bundle/ruby/2.0.0/bin/xcake:22:in `load'
  vendor/bundle/ruby/2.0.0/bin/xcake:22:in `<top (required)>'
```

**Comment by jcampbell05** [comment]
@brennantaylor Do you have an example project as well? I'll try this out, I've been using it with `0.4.0`

**Comment by brennantaylor** [comment]
`0.4.5` works. Just xcake init and that explodes for me.

**Comment by jcampbell05** [comment]
Cool in a future version I'll remove this dependency as @segiddins tole me we could just use Ruby's `tsort`.
